apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: homepage
    decMgmtRequires-b-name: "rbacService"
    decMgmtRequires-b-variable-name: "url"
    decMgmtRequires-b-version: "1.0.0"
  name: homepage
  namespace: homepage
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: schmiddim/service-mock-homepage-service:c882339842dc99253bcbec6703b5e882cc4e4347
#          imagePullPolicy: Never #very important for rancher
          name: homepage-service
          ports:
            - containerPort: 8100
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8100
  selector:
    app: homepage
  type: ClusterIP
